version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: java_db
    restart: always
    ports:
      - "5432:5432" #
    environment:

      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_VALUE}
    volumes:
      - postgres_data_employeemanager:/var/lib/postgresql/data

volumes:
  postgres_data_employeemanager: